import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Word Tree</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={"flex justify-center items-center h-screen"}>
        <div>        
          <div>        
          <h1 className={"text-5xl font-normal leading-normal mt-0 mb-2"}>Word Tree</h1>
        </div>

        <div>
          <div className={"border-solid border-2 border-black rounded p-3 mb-2"}>
            <Link href="/articles" >
              <a className={""}>
                <h2>Articles &rarr;</h2>
                <p>Search keywords in articles</p>
              </a>
            </Link>
          </div>
          <div className={"border-solid border-2 border-black rounded p-3"}>
            <Link href="/keywords" >
              <a className={""}>
                <h2>Keywords &rarr;</h2>
                <p>See keywords and their relationships</p>
              </a>
            </Link>
          </div>
        </div>
      </div>
    </div>
  </div>
  )
}

export default Home
